In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import sys
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [3]:
x = tf.placeholder(tf.float32, shape=[None, 1024])
y_ = tf.placeholder(tf.float32, shape=[None, 10])
training_step = tf.placeholder(tf.float32, shape=[3])

In [4]:
W_conv1 = tf.Variable(tf.random_normal([1,1,1,1],\
                                       stddev = .1),\
                                       name = "W_conv1")
# Input 2D reshape
x_image = tf.reshape(x, [-1, 32, 32, 1])
# Graph construction
h_conv1 = tf.nn.conv2d(x_image, W_conv1, strides=[1, 1, 1, 1], padding='VALID') 
#z_conv1 = tf.nn.relu(h_conv1)
z_conv1 = tf.nn.softmax(h_conv1)

In [5]:
saver = tf.train.Saver()

In [6]:
sess=tf.InteractiveSession()

In [7]:
sess.run(tf.global_variables_initializer()) 

In [8]:
W_conv1.eval()

array([[[[ 0.01802277]]]], dtype=float32)

In [9]:
op = W_conv1.assign([[[[1]]]])
op.eval()

array([[[[ 1.]]]], dtype=float32)

In [10]:
W_conv1.eval()

array([[[[ 1.]]]], dtype=float32)

In [11]:
saver.save(sess, "tmp.ckpt")

'tmp.ckpt'

In [17]:
W_conv1.assign([[[[2]]]]).eval()

array([[[[ 2.]]]], dtype=float32)

In [18]:
W_conv1.eval()

array([[[[ 2.]]]], dtype=float32)

In [19]:
saver.restore(sess, "tmp.ckpt")

INFO:tensorflow:Restoring parameters from tmp.ckpt


In [20]:
W_conv1.eval()

array([[[[ 1.]]]], dtype=float32)